# graysentinel/app/utils/reporting.py
from fpdf import FPDF
from datetime import datetime
import os
from app.models import User
import json

REPORT_DIR = "app/static/reports"

def generate_pdf_report(scan_id, target, scan_type, results, risk_score, user_id):
    if not os.path.exists(REPORT_DIR):
        os.makedirs(REPORT_DIR)
    
    filename = f"report_{scan_id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    filepath = os.path.join(REPORT_DIR, filename)
    
    # Get investigator name
    investigator = User.query.get(user_id)
    investigator_name = investigator.name if investigator else "Unknown"
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    
    # Header
    pdf.cell(0, 10, "GraySentinel OSINT Report", 0, 1, 'C')
    pdf.ln(10)
    
    # Report details
    pdf.set_font("Arial", '', 12)
    pdf.cell(40, 10, "Scan ID:", 0, 0)
    pdf.cell(0, 10, str(scan_id), 0, 1)
    pdf.cell(40, 10, "Target:", 0, 0)
    pdf.cell(0, 10, target, 0, 1)
    pdf.cell(40, 10, "Scan Type:", 0, 0)
    pdf.cell(0, 10, scan_type.capitalize(), 0, 1)
    pdf.cell(40, 10, "Date:", 0, 0)
    pdf.cell(0, 10, datetime.now().strftime("%Y-%m-%d %H:%M:%S"), 0, 1)
    pdf.cell(40, 10, "Investigator:", 0, 0)
    pdf.cell(0, 10, investigator_name, 0, 1)
    pdf.cell(40, 10, "Risk Score:", 0, 0)
    pdf.set_text_color(255, 0, 0) if risk_score > 70 else pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"{risk_score}/100", 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(15)
    
    # Results section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "Scan Results", 0, 1)
    pdf.set_font("Arial", '', 10)
    
    for category, data in results.items():
        pdf.cell(0, 10, f"{category.capitalize()}:", 0, 1, 'L')
        if isinstance(data, list):
            for item in data:
                pdf.multi_cell(0, 7, f"• {item}")
        elif isinstance(data, dict):
            for key, value in data.items():
                pdf.multi_cell(0, 7, f"- {key}: {value}")
        else:
            pdf.multi_cell(0, 7, str(data))
        pdf.ln(2)
    
    # Footer
    pdf.set_y(-15)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, f"Report generated by GraySentinel at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 0, 'C')
    
    pdf.output(filepath)
    return filepath
